// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9JOYJIen2JVXbua5qikppsS26P_atyR4',
    appId: '1:488376797630:web:bfeb71700f8210dd76d1ef',
    messagingSenderId: '488376797630',
    projectId: 'onesignalnotification-f8a0f',
    authDomain: 'onesignalnotification-f8a0f.firebaseapp.com',
    storageBucket: 'onesignalnotification-f8a0f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6fNeYdmF6VT1uH0aEA1aR2zLcorwLkSY',
    appId: '1:488376797630:android:7cbbddb109fba69c76d1ef',
    messagingSenderId: '488376797630',
    projectId: 'onesignalnotification-f8a0f',
    storageBucket: 'onesignalnotification-f8a0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyvdpL1JM2fWGw5GVPTJYKGmpOGz9N8TQ',
    appId: '1:488376797630:ios:0c5f7ee535bb2bf876d1ef',
    messagingSenderId: '488376797630',
    projectId: 'onesignalnotification-f8a0f',
    storageBucket: 'onesignalnotification-f8a0f.appspot.com',
    iosBundleId: 'com.example.umoja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyvdpL1JM2fWGw5GVPTJYKGmpOGz9N8TQ',
    appId: '1:488376797630:ios:0c5f7ee535bb2bf876d1ef',
    messagingSenderId: '488376797630',
    projectId: 'onesignalnotification-f8a0f',
    storageBucket: 'onesignalnotification-f8a0f.appspot.com',
    iosBundleId: 'com.example.umoja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9JOYJIen2JVXbua5qikppsS26P_atyR4',
    appId: '1:488376797630:web:918202fad86cfd4576d1ef',
    messagingSenderId: '488376797630',
    projectId: 'onesignalnotification-f8a0f',
    authDomain: 'onesignalnotification-f8a0f.firebaseapp.com',
    storageBucket: 'onesignalnotification-f8a0f.appspot.com',
  );
}
